# Site settings
title: Bishwo Prakash Dhakal
email: dhakalbishwoprakash@gmail.com
url: https://bishwopr.github.io
description: "Its all about a tiny human bishwo prakash dhakal ."
skills: "Web Developer - Graphic Artist - System Administrator"
meta_author: dhakal bishwoprakash

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: bishwopr

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: No Copy RiGHTS>>>>>>
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/bishwopr
  - title: facebook
    url: http://facebook.com/bishwoprakashd
  - title: github
    url: http://github.com/bishwopr

# Postal address (add as many lines as necessary)
address:
  - line: Chandragiri -03, kathmandu
  - line: Nepal


# Build settings
markdown: kramdown
permalink: pretty
